### ISSUE TITLE
Demo failing to fetch data

### ISSUE THREAD

**Issue by PhearZero** [paulserraino/react-geojson-cluster#7]
[The Demo Data](https://data.texas.gov/resource/9e7h-gz56.json) is throwing a 403 Forbidden Error.

**Comment by paulserraino** [comment]
Yea, it looks like data.texas.gov removed access to their json files via http :/. I'll create some fake geojson data to get this fixed.

**Comment by PhearZero** [comment]
Yea I figured something to that extent. Wanted to test out the geojson-cluster with a koop backend

**Comment by paulserraino** [comment]
all fixed :)
